// build-assets.mjs — reproducible brand raster exports.
//
// Renders the brand SVGs headlessly (Playwright / Chromium) and writes PNGs to
// brand/exports/. Replaces the manual "open preview.html → click 1x/2x/4x" flow:
// the raster assets become *outputs of a command*, not hand-downloaded files.
//
//   npm run build:assets        (from the repo root)
//
// The SVGs themselves are generated by brand/generate-stereonet.js (the master
// SVG generator); this script consumes them. (A later pass moves the logo
// stereonet onto @gcu/bearing and retires the bespoke math + the dead
// stereonet-paths.txt.)

import { chromium } from 'playwright';
import { readFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const BRAND = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(BRAND, 'exports');

// svg → PNG widths (px). Square favicons render square; rectangular logos keep aspect.
const JOBS = [
  { svg: 'gcu-favicon-16.svg', widths: [16, 32] },
  { svg: 'gcu-favicon-32.svg', widths: [32, 48] },
  { svg: 'gcu-favicon-64.svg', widths: [64, 128] },
  { svg: 'gcu-logo-icon.svg', widths: [180, 192, 512] }, // apple-touch · PWA · large
  { svg: 'gcu-logo.svg', widths: [600, 1200] },
  { svg: 'gcu-logo-square.svg', widths: [512, 1024] },
  { svg: 'gcu-malleo.svg', widths: [600, 1200] },
  { svg: 'gcu-malleo-noborder.svg', widths: [600, 1200] },
];

// Prefer the Playwright-managed Chromium (`npx playwright install chromium`); fall back to a
// system Chromium-family browser (Edge/Chrome) so the pipeline runs without a mandatory download.
async function launchBrowser() {
  for (const opts of [undefined, { channel: 'msedge' }, { channel: 'chrome' }]) {
    try {
      return await chromium.launch(opts);
    } catch {
      /* try the next option */
    }
  }
  throw new Error('No Chromium-family browser found. Run: npx playwright install chromium');
}

const browser = await launchBrowser();
const page = await browser.newPage();
await mkdir(OUT, { recursive: true });

let n = 0;
for (const { svg, widths } of JOBS) {
  let markup;
  try {
    markup = await readFile(path.join(BRAND, svg), 'utf8');
  } catch {
    console.warn('  ! missing, skipped:', svg);
    continue;
  }
  for (const w of widths) {
    const side = Math.max(w, 16);
    await page.setViewportSize({ width: side, height: side });
    await page.setContent(
      `<!doctype html><meta charset="utf8">` +
        `<style>html,body{margin:0;background:transparent}svg{display:block;width:${w}px;height:auto}</style>` +
        markup,
      { waitUntil: 'load' },
    );
    const el = await page.$('svg');
    if (!el) {
      console.warn('  ! no <svg> in', svg);
      continue;
    }
    const out = path.join(OUT, `${svg.replace(/\.svg$/, '')}-${w}.png`);
    await el.screenshot({ path: out, omitBackground: true });
    console.log('  ✓', path.relative(BRAND, out));
    n++;
  }
}

await browser.close();
console.log(`\nDone — ${n} PNGs → brand/exports/  (regenerate any time: npm run build:assets)`);
